airbnb:
  outputs:
    dev:
      type: snowflake
      account: vkqhtnc-lk26656
      user: dbt
      role: TRANSFORM

      private_key_path: /Users/amarnadhmovva/dbt_project/rsa_key.p8
      private_key_passphrase: "4365"

      database: AIRBNB
      schema: DEV
      warehouse: COMPUTE_WH
      threads: 1
  target: dev